/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Administrador' at '20/12/16 10:28' with Gradle 2.6
 *
 * @author Administrador, @date 20/12/16 10:28
 */

public class Movie {
	String nombre;
	boolean isRented;
    public boolean isRentableTo(Customer cliente){
    	return true;
    }
}
