import org.junit.Test;
import static org.junit.Assert.*;
import static org.mockito.Mockito.*;
/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'Administrador' at '20/12/16 10:28' with Gradle 2.6
 *
 * @author Administrador, @date 20/12/16 10:28
 */
public class MovieTest {
    @Test public void testSomeLibraryMethod() {
        Movie classUnderTest = new Movie();
        //assertTrue("someLibraryMethod should return 'true'", classUnderTest.someMovieMethod());
    }
}
